module.exports = {

	// Settings
	youtubeChannelId: 'UCQiZv9rSSf288CdT2DudtFQ',
	dealerApiBrand: 'pingpong',
	cacheAge: 31536000,
	browsers: ['> 5%'],

	// Directories,
	views: 'views',
	tasks: 'tasks',
	src: 'src',
	content: 'content',
	dev: 'dev',
	dist: 'public',
	style: 'style',
	script: 'script',
	img: 'img',
	fonts: 'fonts',
	json: 'json',
	svgMapPrefix: 'map-',

	// Toggles modules,
	product: true,
	userAccounts: false,
	ecommerce: true,
	videos: true,
	dealerLocator: false,
	giftWithPurchase: false,
	salsifyJson: true,
	salsifyWebhooks: false,
	static: false,
	staticExtensions: false,
	php: false,
	phpPort: 8888,

	// HTML Minifier Options,
	minifyHtml: true,
	minifyHtmlOptions: {
		removeComments: true,
		removeAttributeQuotes: true,
		removeOptionalTags: true,
		removeEmptyAttributes: true,
		collapseBooleanAttributes: true,
		collapseInlineTagWhitespace: false,
		collapseWhitespace: true,
		decodeEntities: true,
		minifyCSS: true,
		minifyJS: true,
		removeScriptTypeAttributes: true,
		removeStyleLinkTypeAttributes: true,
		sortAttributes: true,
		sortClassName: true
	},

	redirects: {
		301: {
			'/customer-service/contact': '/contact',
			'/customer-service/warranty': '/warranty',

			'/sights': '/category/sights',
			'/arrow-rests': '/category/rests',
			'/quivers': '/category/quivers',
			'/stabilizers': '/category/stabilizers',

			'/sights/react-one-pro': '/product/as701r10',
			'/sights/react-pro': '/product/as825r10',
			'/sights/react-pro-7': '/product/as827r10',
			'/sights/react-h5': '/product/as855',
			'/sights/react-v5': '/product/as845',
			'/sights/fix7': '/product/as907',
			'/sights/fix5': '/product/as905',
			'/sights/fix3': '/product/as903',
			'/sights/react-trio-pro': '/product/as713r19',
			'/sights/cypher-5': '/product/as605',
			'/sights/cypher-3': '/product/as603',
			'/sights/volt': '/product/as109',
			'/sights/joker-4': '/product/as108',
			'/sights/joker-3': '/product/as107',
			'/sights/mist': '/product/as106',
			'/sights/pursuit': '/product/as401r',
			'/sights/drive': '/product/as301',
			'/sights/peak': '/product/as315',

			'/arrow-rests/level': '/product/ada220r',
			'/arrow-rests/hx': '/product/ada110r',
			'/arrow-rests/hxl': '/product/ada210r',
			'/arrow-rests/micro-tack-driver': '/product/atr300r',
			'/arrow-rests/power-shot': '/product/awb600s',
			'/arrow-rests/sure-shot-pro': '/product/awb400rs',
			'/arrow-rests/kill-shot': '/product/awb500s',
			'/arrow-rests/quick-shot': '/product/awb100s',
			'/arrow-rests/original-quick-shot': '/product/awbbrs',

			'/quivers/lite-1': '/product/aq500b',
			'/quivers/vault-two-piece': '/product/aq502',
			'/quivers/5-spot': '/product/aq600b',

			'/stabilizers/static-xs-sidebar': '/product/as1400b',
			'/stabilizers/static-stabilizer': '/product/as1300b',
			'/stabilizers/dart': '/product/as1005b',
		}
	}

}
